### ISSUE TITLE
Make generated PineAPPL grids reproducible

### ISSUE THREAD

**Issue by cschwan** [NNPDF/runcards#109]
For reproducibility reasons we're already putting quite a bit of information into the metadata of the generated PineAPPL grid. However, I think that we can and should improve the situation, especially for Madgraph5 generated grids. In general, I would propose that *reproducibility* means that we can

> easily regenerate the grid *from the metadata alone*, as defined in https://github.com/NNPDF/runcards/issues/109#issuecomment-944148517.

I presume that this is already the case for yadism (as all the runcards are in the metadata), but for Madgraph5 we definitely need more information, in particular the following metadata:

- [x] output.txt and 408fc7a7bfca79e49fb445c2b54573735202722b
- [x] launch.txt, each with variables substituted by their numerical values 408fc7a7bfca79e49fb445c2b54573735202722b
- [x] and all modifications of the Madgraph5 source code bundled in a patch. d772102

**Comment by AleCandido** [comment]
Runcards added to madgraph generated grids with `launch.txt` and `output.txt` keys 408fc7a7bfca79e49fb445c2b54573735202722b.

**Comment by AleCandido** [comment]
I decided that merging patches is a too complex operation, and we already store the git version of `runcards` repo, so we can rely on patches and cuts that are shipped with the repo/the package.

Thus in d772102 I added to metadata:
- `patches`, i.e. a list of patches' names, one per row
- `tau_min`, i.e. the min tau value, if present
- `user_cuts`, i.e. user defined cuts and cuts values, one per row in the format `cut=value`

I still need to document, so I would not close the issue until I'll have done it.
Furthermore there is to decide if keeping the cuts & patches both inside the package, or both outside (at the moment cuts are inside, but patches outside, and this is inconsistent).

**Comment by AleCandido** [comment]
Documentation added in b05f01ab9f2a04152386a962f536bde9df2c54b9.

Now I'd close, do you think there is still anything to do @cschwan?

**Comment by cschwan** [comment]
@AleCandido

- where can I read the documentation online? We should add a badge for that or at least a link
- I'd keep the Issue open, as it isn't fixed (but as I said, not really a problem)

**Comment by felixhekhorn** [comment]
Someone has to activate the project on readthedocs - the configuration is already there ... when I look there, I can't activate the repo since it is not listed in my projects (only N3PDF repos) ...

**Comment by cschwan** [comment]
@scarrazza I think the problem is that this repository isn't N3PDF but NNPDF. Should we migrate it together with the renaming?

**Comment by AleCandido** [comment]
Sorry not to have replied before, since it is public documentation has been deployed at https://runcars.readthedocs.io/en/latest/

(notice that, for an unknown reason, is deployed at `runcars` rather than `runcards`, but since we're about to switch name I'd not bother to change it)

**Comment by AleCandido** [comment]
>  * I'd keep the Issue open, as it isn't fixed (but as I said, not really a problem)

What do you still want from this one? From the point of view of saving the information I believe we have everything.

Maybe you would like to have a streamlined way to run from a pineapplgrid, rather than having to reconstruct the runcard (and maybe in this case I could store in the metadata which external has been used, to make it easier to pick that one). If so, please add this among the tasks in the OP.

**Comment by cschwan** [comment]
> Sorry not to have replied before, since it is public documentation has been deployed at https://runcars.readthedocs.io/en/latest/
> 
> (notice that, for an unknown reason, is deployed at `runcars` rather than `runcards`, but since we're about to switch name I'd not bother to change it)

Runcars, I like it :grin: !

**Comment by felixhekhorn** [comment]
I guess this issue is completed?

**Comment by AleCandido** [comment]
> Runcars, I like it :grin: !

To be honest, I noticed a while ago, but I didn't figure why...
