### ISSUE TITLE
Problem with ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/runcards#114]
pineapplname: https://github.com/NNPDF/runcards/blob/master/nnpdf31_proc/ATLAS_TTB_8TEV_LJ_TTM

We are seeing an issue with this dataset (more specifically with the NNPDF-pineappl translation). If we use it as is, it does not work:

```python
from validphys.api import API
API.dataset(dataset_input={"dataset":"ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM"}, theoryid=208, use_cuts="internal")
```
```
ConfigError: Incorrect COMPOUND file '/usr/local/share/NNPDF/data/theory_208/compound/FK_ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM-COMPOUND.dat'. Searching for non-existing FKTable:
Could not find FKTable for set 'ATLASTOPDIFF8TEVTTM_NUM'. File '/usr/local/share/NNPDF/data/theory_208/fastkernel/FK_ATLASTOPDIFF8TEVTTM_NUM.dat' not found

```

If we look at the dataset in theory 208 we see that it is a compound dataset, but the FKTables that "compose it" are nowhere to be found.
```
# COMPOUND FK
FK: FK_ATLASTOPDIFF8TEVTTM_NUM.dat
FK: FK_ATLASTOPDIFF8TEVTTM_DEN.dat
OP: RATIO
```
None of these are in Theory 208.

The same is true for the TPT version https://github.com/NNPDF/runcards/tree/master/nnpdf31_proc/ATLAS_TTB_8TEV_LJ_TPT

We are not sure whether it is a problem with the NNPDF theory, the translation layer or whether it is something else

@scarlehoff

---
For @cschwan:

The files of interest are (in dom)
compound: /usr/local/share/NNPDF/data/theory_208/compound/FK_ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM-COMPOUND.dat

fk folder: /usr/local/share/NNPDF/data/theory_208/fastkernel/

**Comment by enocera** [comment]
@felixhekhorn Theory 208 DOES not have the FK tables for the dataset you're mentioning on purpose. The dataset is not part of NNPDF4.0, because it is excluded by our selection criteria. The FK tables for that data set are only in theory 200, which was indeed used to decide whether or not to include the dataset. That being said, I must modify theory 208 by removing the compound files for the datasets that are not available.

**Comment by enocera** [comment]
For all practical purpose, I'd say that you can safely ignore 'ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM`. And similarly `ATLAS_TTB_DIFF_8TEV_LJ_PTNORM`.

**Comment by scarlehoff** [comment]
Indeed. The same problem was seen for the PT. I was wondering how come I never saw this problem during the fits. Thanks!
