### ISSUE TITLE
Problem with poetry

### ISSUE THREAD

**Issue by cschwan** [NNPDF/runcards#122]
```
WARNING: You are using pip version 20.3.3; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "./rr", line 113, in <module>
    subprocess.run("poetry install".split())
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in _init_
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'poetry': 'poetry'
```

_Originally posted by @marcozaro in https://github.com/NNPDF/runcards/issues/121#issuecomment-1010845839_

**Comment by AleCandido** [comment]
https://github.com/NNPDF/runcards/blob/70396b76f72502fef1f549dcd450fa92d66fd610/README.md#L16-L19
Is this not enough?

**Comment by cschwan** [comment]
No, it wasn't.

**Comment by AleCandido** [comment]
Then we need more information. `poetry` is not available as a package, but `./rr install` should have made it available.

So we need him to run:
```sh
pip list | grep poetry
./rr install
pip list | grep poetry
```
And please give even the full output of `./rr install`.

**Comment by cschwan** [comment]
@marcozaro ?

**Comment by marcozaro** [comment]
pip list | grep poetry
poetry-dynamic-versioning 0.13.1

**Comment by AleCandido** [comment]
Feel free to uninstall `poetry-dynamic-versioning` if it's causing you problems.
In principle, you just need to properly tag your grids with `runcards` version (including commit sha if `dirty`).

**Comment by marcozaro** [comment]
Hi,
so 
pip3 install poetry gives a lot of things, and ends with...

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dunamai 1.7.0 requires importlib-metadata>=2.1.1; python_version < "3.8", but you have importlib-metadata 1.7.0 which is incompatible.

probably it is related to the fact that I have python 3.7.3....

Cheers,

Marco

**Comment by AleCandido** [comment]
In principle this the requirements of `poetry 1.1.x`:

```sh
python = "~2.7 || ^3.5"
```
https://github.com/python-poetry/poetry/blob/43943ba62f2eb7ea78687704bb5cef930cb830d5/pyproject.toml#L25

while on master it is:
```sh
python = "^3.6"
```
https://github.com/python-poetry/poetry/blob/ecb030e1f0b7c13cc11971f00ee5012e82a892bc/pyproject.toml#L35

**Comment by AleCandido** [comment]
Sorry to have done it in two steps, but try using the suggested installer via `curl` (I amended the former comment, maybe later than you read it :disappointed:)

**Comment by cschwan** [comment]
@marcozaro if I read your error message properly, `importlib-metadata` should be upgraded. Does

```
pip install -U importlib-metadata
```

do the trick?

**Comment by AleCandido** [comment]
It's not my error message, that is coming directly from `pip`.

Poetry recommended installation method (from [website](https://python-poetry.org/docs/#installation)) is:
```sh
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
```
(actually website say to run with `python`, added the `3` myself to be sure)
