### ISSUE TITLE
Add positivity observables

### ISSUE THREAD

**Issue by cschwan** [NNPDF/runcards#124]
Do we want a generator in this repository for the positivity observables? This would be basically https://github.com/N3PDF/pineappl/blob/master/examples/python/positivity.py.

**Comment by cschwan** [comment]
That was my train of though also. I'd volunteer to take care of it, if you're busy with other projects.

**Comment by AleCandido** [comment]
We're slowly completing most of the chores, but still I would not do it before ~10 days. If you can start, do it :)

Were you thinking something about a new backend (like `yadism`, `mg5`, and conversions the moment we'll get there), a new subcommand, or just moving the script?

**Comment by cschwan** [comment]
> We're slowly completing most of the chores, but still I would not do it before ~10 days. If you can start, do it :)
> 
> Were you thinking something about a new backend (like `yadism`, `mg5`, and conversions the moment we'll get there), a new subcommand, or just moving the script?

I was thinking about making it a new backend, which isn't too complicated given that we already have that script.

**Comment by cschwan** [comment]
OK, thanks for your pointers, let me try to implement it!

**Comment by felixhekhorn** [comment]
>     * `collect_versions`: not needed, this backend would be fully integrated in the runner x

then it should be the runner version

**Comment by AleCandido** [comment]
runner version is included always by default:
https://github.com/NNPDF/runcards/blob/500e06c14cf2b42c2897fd6360fc0df347af6516/runcardsrunner/external/interface.py#L110-L116

(even though maybe we can even drop `pygit2` at some point, and try to use the `poetry-dynamic-versioning` provided one, they should coincide)

**Comment by felixhekhorn** [comment]
yes, I meant just not to leave it empty or something, but put the version twice (such that one can guess the generator, i.e. if they are the same the generator is built-in)

**Comment by AleCandido** [comment]
No, why twice? It is redundant, and runner is runner, so leave it empty.

Consider that there is no *standard field* for `external`, yadism add a `yadism_version`, and mg5 add an `mg5_version`. Here there is nothing but the runner, so leave it empty.

**Comment by AleCandido** [comment]
If you want to log the generator used let's add a separate field, and make it explicit (even though it might already been logged somewhere, but I'm not sure).
