### ISSUE TITLE
Comparison to MC

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/runcards#131]
> I actually checked everything (but 1 CHORUS runcard, NU one, that is still running) and the problem is solved.
> 
> If anyone would like to confirm, it'd be perfect. Otherwise, I'd claim it as fixed.

@AleCandido 

I still get weird numbers (which I'm ignoring for now, since we believe it to be only a problem of comparison)
```
$ tail CHORUS_CC_NB_PB_SIGMARED-20220215120859/results.log 
595  7.756149e-02  7.756149e-02   0.000   0.000   0.0000 1133.6003  841.3525
596  1.267895e-03  1.267895e-03   0.000   0.000   0.0000 1001.4562  996.3702
597  1.435001e-03  1.435001e-03   0.000   0.000   0.0000 1001.8782  996.9110
598  1.747103e-02  1.747103e-02   0.000   0.000   0.0000 1029.4459  968.2160
599  1.308383e-02  1.308383e-02   0.000   0.000   0.0000 1021.9180  972.1292
600  8.438453e-03  8.438453e-03   0.000   0.000   0.0000 1014.0529  984.6104
601  2.934333e-02  2.934333e-02   0.000   0.000   0.0000 1050.1052  939.4943
602  2.811828e-02  2.811828e-02   0.000   0.000   0.0000 1047.6338  949.0632
603  1.377383e-03  1.377383e-03   0.000   0.000   0.0000 1001.8341  997.0856
604  8.102164e-03  8.102164e-03   0.000   0.000   0.0000 1013.5296  985.3849
```

_Originally posted by @felixhekhorn in https://github.com/NNPDF/runcards/issues/117#issuecomment-1044349708_

**Comment by AleCandido** [comment]
This problem is not present on my locally computed grid `CHORUS_CC_NB_PB_SIGMARED-20220215230008`, so I believe this to be still a version problem.

I'm recomputing (locally) with current version, to check again.

**Comment by AleCandido** [comment]
It keeps working locally on my desktop, I believe there is really something outdated.

**Comment by felixhekhorn** [comment]
If only I take the correct grid, i.e. `CHORUS_CC_NB_PB_SIGMARED-20220218123325` there is no problem :see_no_evil:
