### ISSUE TITLE
Error during linking with CC

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/runcards#137]
For some reasons I couldn't exactly figure out yet, there is an error when linking to the `cc` during the installation of `pineappl`. This causes the command `./rr run <folder> <theory>` to crash. Here are the [logs](https://github.com/NNPDF/runcards/files/8771215/log.txt) from running that command. In case it might be useful, here are the [logs](https://github.com/NNPDF/runcards/files/8771233/run_01_tag_1_debug.log) during the `MadGraph` run. I can install `PineAPPL` independently but I was wondering what could the cause of this?

PS: All the dependencies are installed in a `CONDA` environment and the only modification I had to do, given that i do not have permission write on the user's directory on the cluster, was at the level of the `rr` script:
```python
if __name__ == "__main__":
    os.environ["HOME"] = "/data/theorie/tanjona/"
    os.environ["PATH"] += os.pathsep + "/data/theorie/tanjona/.local/bin"
    # os.environ["PATH"] += os.pathsep + "/data/theorie/tanjona/anaconda3/envs/madpineappl/bin/"
```

**Comment by cschwan** [comment]
This seems to be caused by having two (?) different compilers and possibly incomplete environment variables. Could you try to install/run everything outside your CONDA environment?

**Comment by cschwan** [comment]
For the final runs we'll have to decide which values of MW we'd like to scan, but we can talk about that tomorrow during the PC.

**Comment by Radonirinaunimi** [comment]
> @Radonirinaunimi it's not enough, but it's a check of whether we have enough statistics. For each bin the MC uncertainty should be well below the change induced by changing MW.

Yes! Let's indeed see how the results look like once the runs are over.

> For the final runs we'll have to decide which values of MW we'd like to scan, but we can talk about that tomorrow during the PC.

Sounds good!

**Comment by enocera** [comment]
@Radonirinaunimi Just for the record, here's the link to the Nikhef wiki web page with explanations on how to make use of modern compilers and other pieces of code https://wiki.nikhef.nl/grid/Modern_C_Compiler,_ROOT,_Geant

**Comment by Radonirinaunimi** [comment]
> @Radonirinaunimi Just for the record, here's the link to the Nikhef wiki web page with explanations on how to make use of modern compilers and other pieces of code https://wiki.nikhef.nl/grid/Modern_C_Compiler,_ROOT,_Geant

Thanks a lot @enocera ! This documentation is incredibly useful.
