### ISSUE TITLE
Download mg5amc using git

### ISSUE THREAD

**Issue by cschwan** [NNPDF/runcards#142]
Their new repository is now on github: <https://github.com/mg5amcnlo/mg5amcnlo>. We should use the [3.4.1 branch](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.4.1), which includes the [bias reweighting patch](https://github.com/mg5amcnlo/mg5amcnlo/commit/c586517c58169d220314280dc6aa1ab6decb9c37) that might be needed in the future.

**Comment by AleCandido** [comment]
I would close this in favor of #145. I updated it to include information here.

Do you agree? @cschwan
